# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatPrivado.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChatPrivado.proto',
  package='ChatPrivado',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x43hatPrivado.proto\x12\x0b\x43hatPrivado\"Z\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"1\n\x0c\x43hatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t2\x98\x01\n\x0b\x43hatService\x12\x42\n\x0bSendMessage\x12\x18.ChatPrivado.ChatMessage\x1a\x19.ChatPrivado.ChatResponse\x12\x45\n\x0eReceiveMessage\x12\x18.ChatPrivado.ChatMessage\x1a\x19.ChatPrivado.ChatResponseb\x06proto3')
)




_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='ChatPrivado.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='ChatPrivado.ChatMessage.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='ChatPrivado.ChatMessage.receiver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='ChatPrivado.ChatMessage.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='ChatPrivado.ChatMessage.port', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ChatPrivado.ChatMessage.message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=124,
)


_CHATRESPONSE = _descriptor.Descriptor(
  name='ChatResponse',
  full_name='ChatPrivado.ChatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ChatPrivado.ChatResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='ChatPrivado.ChatResponse.response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['ChatResponse'] = _CHATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), dict(
  DESCRIPTOR = _CHATMESSAGE,
  __module__ = 'ChatPrivado_pb2'
  # @@protoc_insertion_point(class_scope:ChatPrivado.ChatMessage)
  ))
_sym_db.RegisterMessage(ChatMessage)

ChatResponse = _reflection.GeneratedProtocolMessageType('ChatResponse', (_message.Message,), dict(
  DESCRIPTOR = _CHATRESPONSE,
  __module__ = 'ChatPrivado_pb2'
  # @@protoc_insertion_point(class_scope:ChatPrivado.ChatResponse)
  ))
_sym_db.RegisterMessage(ChatResponse)



_CHATSERVICE = _descriptor.ServiceDescriptor(
  name='ChatService',
  full_name='ChatPrivado.ChatService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=178,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='ChatPrivado.ChatService.SendMessage',
    index=0,
    containing_service=None,
    input_type=_CHATMESSAGE,
    output_type=_CHATRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReceiveMessage',
    full_name='ChatPrivado.ChatService.ReceiveMessage',
    index=1,
    containing_service=None,
    input_type=_CHATMESSAGE,
    output_type=_CHATRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHATSERVICE)

DESCRIPTOR.services_by_name['ChatService'] = _CHATSERVICE

# @@protoc_insertion_point(module_scope)
