# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Client_Server_pb2 as Client__Server__pb2


class RedisServiceStub(object):
  """Definición del servicio de registro.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterClient = channel.unary_unary(
        '/Client_Server.RedisService/RegisterClient',
        request_serializer=Client__Server__pb2.ClientInfo.SerializeToString,
        response_deserializer=Client__Server__pb2.RegisterResponse.FromString,
        )
    self.GiveParameters = channel.unary_unary(
        '/Client_Server.RedisService/GiveParameters',
        request_serializer=Client__Server__pb2.ClientName.SerializeToString,
        response_deserializer=Client__Server__pb2.ClientParams.FromString,
        )


class RedisServiceServicer(object):
  """Definición del servicio de registro.
  """

  def RegisterClient(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GiveParameters(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RedisServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterClient': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterClient,
          request_deserializer=Client__Server__pb2.ClientInfo.FromString,
          response_serializer=Client__Server__pb2.RegisterResponse.SerializeToString,
      ),
      'GiveParameters': grpc.unary_unary_rpc_method_handler(
          servicer.GiveParameters,
          request_deserializer=Client__Server__pb2.ClientName.FromString,
          response_serializer=Client__Server__pb2.ClientParams.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Client_Server.RedisService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
